name: Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  notify_telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Send message to Telegram
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="Novo push na branch main do repositório CyberPress!"